"""add prompt_additions on brand and project

Revision ID: d714e5ac0787
Revises: e36934ed28e5
Create Date: 2026-04-20 19:06:08.680706

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d714e5ac0787"
down_revision: Union[str, None] = "e36934ed28e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "brands",
        sa.Column(
            "prompt_additions",
            sa.String(length=4000),
            nullable=False,
            server_default="",
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "prompt_additions",
            sa.String(length=4000),
            nullable=False,
            server_default="",
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "prompt_additions")
    op.drop_column("brands", "prompt_additions")
    # ### end Alembic commands ###
